class Exercise {
  final String? id;
  final String name;
  final String equipment;
  final List<String> musclesUsed;
  final String exerciseCategory;
  final String limbInvolvement;
  final String link;
  final String note;
  final String? userID;

  Exercise({
    this.id,
    required this.name,
    required this.equipment,
    required this.musclesUsed,
    required this.exerciseCategory,
    required this.limbInvolvement,
    required this.link,
    required this.note,
    this.userID,
  });

  Map<String, Object?> toJSON() {
    return {
      ExerciseFields.id: id,
      ExerciseFields.name: name,
      ExerciseFields.equipment: equipment,
      ExerciseFields.musclesUsed: musclesUsed,
      ExerciseFields.exerciseCategory: exerciseCategory,
      ExerciseFields.limbInvolvement: limbInvolvement,
      ExerciseFields.link: link,
      ExerciseFields.note: note,
      ExerciseFields.userID: userID,
    };
  }

  static Exercise fromJSON(json) {
    List<dynamic> musclesUsed = json[ExerciseFields.musclesUsed];
    List<String> listMusclesUsed = List<String>.from(musclesUsed);

    return Exercise(
      id: json[ExerciseFields.id] as String?,
      name: json[ExerciseFields.name] as String,
      equipment: json[ExerciseFields.equipment] as String,
      musclesUsed: listMusclesUsed,
      exerciseCategory: json[ExerciseFields.exerciseCategory] as String,
      limbInvolvement: json[ExerciseFields.limbInvolvement] as String,
      link: json[ExerciseFields.link] as String,
      note: json[ExerciseFields.note] as String,
      userID: json[ExerciseFields.userID] as String?,
    );
  }

  Exercise copy({
    String? id,
    String? name,
    String? equipment,
    List<String>? musclesUsed,
    String? exerciseCategory,
    String? limbInvolvement,
    String? link,
    String? note,
    String? userID,
  }) {
    return Exercise(
      id: id ?? this.id,
      name: name ?? this.name,
      equipment: equipment ?? this.equipment,
      musclesUsed: musclesUsed ?? this.musclesUsed,
      exerciseCategory: exerciseCategory ?? this.exerciseCategory,
      limbInvolvement: limbInvolvement ?? this.limbInvolvement,
      link: link ?? this.link,
      note: note ?? this.note,
      userID: userID ?? this.userID,
    );
  }
}

class ExerciseFields {
  static String id = 'id';
  static String name = 'name';
  static String equipment = 'equipment';
  static String musclesUsed = 'musclesUsed';
  static String exerciseCategory = 'exerciseCategory';
  static String limbInvolvement = 'limbInvolvement';
  static String link = 'link';
  static String note = 'note';
  static String userID = 'userID';
}

class ExerciseCategory {
  static String lowerPush = 'Lower Push';
  static String lowerPull = 'Lower Pull';
  static String upperPush = 'Upper Push';
  static String upperPull = 'Upper Pull';
  static String arms = 'Arms';
  static String trunk = 'Trunk';
  static String other = 'Other';

  static List<String> all = [
    lowerPull,
    upperPull,
    lowerPush,
    upperPush,
    arms,
    trunk,
    other,
  ];
}

class LimbInvolvement {
  static String bilateral = 'Bilateral';
  static String unilateral = 'Unilateral';

  static List<String> all = [
    unilateral,
    bilateral,
  ];
}

class Equipment {
  static String bodyweight = 'Bodyweight';
  static String barbell = 'Barbell';
  static String dumbbell = 'Dumbbell';
  static String resistanceBand = 'ResistanceBand';
  static String machine = 'Machine';
  static String other = 'Other';

  static List<String> all = [
    bodyweight,
    barbell,
    dumbbell,
    resistanceBand,
    machine,
    other,
  ];
}

List<Exercise> defaultExercises = [
  Exercise(
    id: '1',
    name: 'Barbell Step Up',
    equipment: Equipment.barbell,
    musclesUsed: ['Quad', 'Glute'],
    exerciseCategory: ExerciseCategory.lowerPush,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '2',
    name: 'Barbell FFESS',
    equipment: Equipment.barbell,
    musclesUsed: ['Glute', 'Quad'],
    exerciseCategory: ExerciseCategory.lowerPush,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '3',
    name: 'Barbell RFESS',
    equipment: Equipment.barbell,
    musclesUsed: ['Glute', 'Quad'],
    exerciseCategory: ExerciseCategory.lowerPush,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '4',
    name: 'Barbell Lateral Lunge',
    equipment: Equipment.barbell,
    musclesUsed: ['Glute', 'Quad'],
    exerciseCategory: ExerciseCategory.lowerPush,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '5',
    name: 'Barbell Lunge',
    equipment: Equipment.barbell,
    musclesUsed: ['Glute', 'Quad'],
    exerciseCategory: ExerciseCategory.lowerPush,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '6',
    name: 'Pistol Squat',
    equipment: Equipment.bodyweight,
    musclesUsed: ['Quad', 'Glute'],
    exerciseCategory: ExerciseCategory.lowerPush,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '7',
    name: 'Step Down',
    equipment: Equipment.dumbbell,
    musclesUsed: ['Quad', 'Glute'],
    exerciseCategory: ExerciseCategory.lowerPush,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '8',
    name: 'SL Leg Press',
    equipment: Equipment.machine,
    musclesUsed: ['Quad', 'Glute'],
    exerciseCategory: ExerciseCategory.lowerPush,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '9',
    name: 'SL Knee Extension',
    equipment: Equipment.machine,
    musclesUsed: ['Quad', ''],
    exerciseCategory: ExerciseCategory.lowerPush,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '10',
    name: 'Dumbbell Step Up',
    equipment: Equipment.dumbbell,
    musclesUsed: ['Quad', 'Glute'],
    exerciseCategory: ExerciseCategory.lowerPush,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '11',
    name: 'Dumbbell FFESS',
    equipment: Equipment.dumbbell,
    musclesUsed: ['Glute', 'Quad'],
    exerciseCategory: ExerciseCategory.lowerPush,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '12',
    name: 'Dumbbell RFESS',
    equipment: Equipment.dumbbell,
    musclesUsed: ['Glute', 'Quad'],
    exerciseCategory: ExerciseCategory.lowerPush,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '13',
    name: 'Dumbbell Lateral Lunge',
    equipment: Equipment.dumbbell,
    musclesUsed: ['Glute', 'Quad'],
    exerciseCategory: ExerciseCategory.lowerPush,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '14',
    name: 'Dumbbell Lunge',
    equipment: Equipment.dumbbell,
    musclesUsed: ['Glute', 'Quad'],
    exerciseCategory: ExerciseCategory.lowerPush,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '15',
    name: 'Back Squat',
    equipment: Equipment.barbell,
    musclesUsed: ['Quad', 'Glute', 'Lower Back'],
    exerciseCategory: ExerciseCategory.lowerPush,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '16',
    name: 'Banded Squat',
    equipment: Equipment.barbell,
    musclesUsed: ['Quad', 'Glute', 'Lower Back'],
    exerciseCategory: ExerciseCategory.lowerPush,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '17',
    name: 'Box Squat',
    equipment: Equipment.barbell,
    musclesUsed: ['Quad', 'Glute', 'Lower Back'],
    exerciseCategory: ExerciseCategory.lowerPush,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '18',
    name: 'Close Stance Squat',
    equipment: Equipment.barbell,
    musclesUsed: ['Quad', 'Glute'],
    exerciseCategory: ExerciseCategory.lowerPush,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '19',
    name: 'Front Squat',
    equipment: Equipment.barbell,
    musclesUsed: ['Quad', 'Glute'],
    exerciseCategory: ExerciseCategory.lowerPush,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '20',
    name: 'Leg Extension',
    equipment: Equipment.machine,
    musclesUsed: ['Quad', ''],
    exerciseCategory: ExerciseCategory.lowerPush,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '21',
    name: 'Leg Press',
    equipment: Equipment.machine,
    musclesUsed: ['Quad', 'Glute'],
    exerciseCategory: ExerciseCategory.lowerPush,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '22',
    name: 'Lowbar Squat',
    equipment: Equipment.barbell,
    musclesUsed: ['Quad', 'Glute', 'Lower Back'],
    exerciseCategory: ExerciseCategory.lowerPush,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '23',
    name: 'Pin Squat',
    equipment: Equipment.barbell,
    musclesUsed: ['Quad', 'Glute', 'Lower Back'],
    exerciseCategory: ExerciseCategory.lowerPush,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '24',
    name: 'Hamstring Curl',
    equipment: Equipment.machine,
    musclesUsed: ['Hamstring', ''],
    exerciseCategory: ExerciseCategory.lowerPull,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '25',
    name: 'Nordic Curl',
    equipment: Equipment.bodyweight,
    musclesUsed: ['Hamstring', ''],
    exerciseCategory: ExerciseCategory.lowerPull,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '26',
    name: 'Swissball Hamstring Curl',
    equipment: Equipment.bodyweight,
    musclesUsed: ['Hamstring', ''],
    exerciseCategory: ExerciseCategory.lowerPull,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '27',
    name: 'Slider Hamstring Curl',
    equipment: Equipment.bodyweight,
    musclesUsed: ['Hamstring', ''],
    exerciseCategory: ExerciseCategory.lowerPull,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '28',
    name: 'Band Hamstring Curl',
    equipment: Equipment.resistanceBand,
    musclesUsed: ['Hamstring', ''],
    exerciseCategory: ExerciseCategory.lowerPull,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '29',
    name: 'Single Leg RDL',
    equipment: Equipment.dumbbell,
    musclesUsed: ['Hamstring', 'Glute'],
    exerciseCategory: ExerciseCategory.lowerPull,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '30',
    name: 'Landmine Single Leg RDL',
    equipment: Equipment.barbell,
    musclesUsed: ['Hamstring', 'Glute'],
    exerciseCategory: ExerciseCategory.lowerPull,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '31',
    name: 'Staggered Stance RDL',
    equipment: Equipment.barbell,
    musclesUsed: ['Hamstring', 'Glute', 'Lower Back'],
    exerciseCategory: ExerciseCategory.lowerPull,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '32',
    name: 'Sorensen Hold',
    equipment: Equipment.bodyweight,
    musclesUsed: ['Hamstring', 'Glute', 'Lower Back'],
    exerciseCategory: ExerciseCategory.lowerPull,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '33',
    name: 'SL Sorensen Hold',
    equipment: Equipment.bodyweight,
    musclesUsed: ['Hamstring', 'Glute', 'Lower Back'],
    exerciseCategory: ExerciseCategory.lowerPull,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '34',
    name: 'Hamstring Bridge',
    equipment: Equipment.bodyweight,
    musclesUsed: ['Hamstring', ''],
    exerciseCategory: ExerciseCategory.lowerPull,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '35',
    name: 'RDL',
    equipment: Equipment.barbell,
    musclesUsed: ['Hamstring', 'Glute', 'Lower Back'],
    exerciseCategory: ExerciseCategory.lowerPull,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '36',
    name: 'Hamstring March',
    equipment: Equipment.bodyweight,
    musclesUsed: ['Hamstring', ''],
    exerciseCategory: ExerciseCategory.lowerPull,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '37',
    name: 'Deadlift',
    equipment: Equipment.barbell,
    musclesUsed: ['Lower Back', 'Glute', 'Hamstring'],
    exerciseCategory: ExerciseCategory.lowerPull,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '38',
    name: 'Trapbar Deadlift',
    equipment: Equipment.barbell,
    musclesUsed: ['Glute', 'Lower Back', 'Hamstring'],
    exerciseCategory: ExerciseCategory.lowerPull,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '39',
    name: 'Hip Thurst',
    equipment: Equipment.barbell,
    musclesUsed: ['Glute', ''],
    exerciseCategory: ExerciseCategory.lowerPull,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '40',
    name: 'Rack Pull',
    equipment: Equipment.barbell,
    musclesUsed: ['Lower Back', 'Hamstring', 'Glute'],
    exerciseCategory: ExerciseCategory.lowerPull,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '41',
    name: 'Back Extension',
    equipment: Equipment.bodyweight,
    musclesUsed: ['Glute', 'Hamstring', 'Lower Back'],
    exerciseCategory: ExerciseCategory.lowerPull,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '42',
    name: 'Bench Press',
    equipment: Equipment.barbell,
    musclesUsed: ['Chest', 'Triceps', 'Shoulders'],
    exerciseCategory: ExerciseCategory.upperPush,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '43',
    name: 'Dumbbell Bench Press',
    equipment: Equipment.dumbbell,
    musclesUsed: ['Chest', ''],
    exerciseCategory: ExerciseCategory.upperPush,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '44',
    name: 'Dumbbell Incline Press',
    equipment: Equipment.dumbbell,
    musclesUsed: ['Chest', 'Shoulders'],
    exerciseCategory: ExerciseCategory.upperPush,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '45',
    name: 'Dumbbell OH Press',
    equipment: Equipment.dumbbell,
    musclesUsed: ['Shoulders', 'Triceps'],
    exerciseCategory: ExerciseCategory.upperPush,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '46',
    name: 'Dips',
    equipment: Equipment.bodyweight,
    musclesUsed: ['Triceps', 'Chest'],
    exerciseCategory: ExerciseCategory.upperPush,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '47',
    name: 'Front Raise',
    equipment: Equipment.dumbbell,
    musclesUsed: ['Shoulders', ''],
    exerciseCategory: ExerciseCategory.upperPush,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '48',
    name: 'Incline Pec Fly',
    equipment: Equipment.dumbbell,
    musclesUsed: ['Chest', ''],
    exerciseCategory: ExerciseCategory.upperPush,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '49',
    name: 'Incline Press',
    equipment: Equipment.barbell,
    musclesUsed: ['Chest', 'Shoulders'],
    exerciseCategory: ExerciseCategory.upperPush,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '50',
    name: 'Lateral Raise',
    equipment: Equipment.dumbbell,
    musclesUsed: ['Shoulders', ''],
    exerciseCategory: ExerciseCategory.upperPush,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '51',
    name: 'Barbell Overhead Press',
    equipment: Equipment.barbell,
    musclesUsed: ['Shoulders', ''],
    exerciseCategory: ExerciseCategory.upperPush,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '52',
    name: 'Pec Flys',
    equipment: Equipment.dumbbell,
    musclesUsed: ['Chest', ''],
    exerciseCategory: ExerciseCategory.upperPush,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '53',
    name: 'Push Up',
    equipment: Equipment.bodyweight,
    musclesUsed: ['Triceps', 'Chest'],
    exerciseCategory: ExerciseCategory.upperPush,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '54',
    name: 'Band Pullapart',
    equipment: Equipment.resistanceBand,
    musclesUsed: ['Back', ''],
    exerciseCategory: ExerciseCategory.upperPull,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '55',
    name: 'Barbell Shrugg',
    equipment: Equipment.barbell,
    musclesUsed: ['Back', ''],
    exerciseCategory: ExerciseCategory.upperPull,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '56',
    name: 'Bench Pull',
    equipment: Equipment.barbell,
    musclesUsed: ['Back', 'Biceps'],
    exerciseCategory: ExerciseCategory.upperPull,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '57',
    name: 'Bentover Row',
    equipment: Equipment.barbell,
    musclesUsed: ['Back', 'Biceps'],
    exerciseCategory: ExerciseCategory.upperPull,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '58',
    name: 'Cable Row',
    equipment: Equipment.machine,
    musclesUsed: ['Back', 'Biceps'],
    exerciseCategory: ExerciseCategory.upperPull,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '59',
    name: 'Chest Supported Row',
    equipment: Equipment.machine,
    musclesUsed: ['Back', 'Biceps'],
    exerciseCategory: ExerciseCategory.upperPull,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '60',
    name: 'Chin Up',
    equipment: Equipment.bodyweight,
    musclesUsed: ['Back', 'Biceps'],
    exerciseCategory: ExerciseCategory.upperPull,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '61',
    name: 'Dumbbell Shrugg',
    equipment: Equipment.dumbbell,
    musclesUsed: ['Back', ''],
    exerciseCategory: ExerciseCategory.upperPull,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '62',
    name: 'Face Pull',
    equipment: Equipment.machine,
    musclesUsed: ['Back', ''],
    exerciseCategory: ExerciseCategory.upperPull,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '63',
    name: 'Inverted Row',
    equipment: Equipment.bodyweight,
    musclesUsed: ['Back', 'Biceps'],
    exerciseCategory: ExerciseCategory.upperPull,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '64',
    name: 'Lat Pulldown',
    equipment: Equipment.machine,
    musclesUsed: ['Back', 'Biceps'],
    exerciseCategory: ExerciseCategory.upperPull,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '65',
    name: 'Machine Row',
    equipment: Equipment.machine,
    musclesUsed: ['Back', 'Biceps'],
    exerciseCategory: ExerciseCategory.upperPull,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '66',
    name: 'Pendlay Row',
    equipment: Equipment.barbell,
    musclesUsed: ['Back', 'Biceps'],
    exerciseCategory: ExerciseCategory.upperPull,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '67',
    name: 'Prone Flys',
    equipment: Equipment.dumbbell,
    musclesUsed: ['Back', ''],
    exerciseCategory: ExerciseCategory.upperPull,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '68',
    name: 'Pull Up',
    equipment: Equipment.bodyweight,
    musclesUsed: ['Back', 'Biceps'],
    exerciseCategory: ExerciseCategory.upperPull,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '69',
    name: 'Pullover',
    equipment: Equipment.dumbbell,
    musclesUsed: ['Back', ''],
    exerciseCategory: ExerciseCategory.upperPull,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '70',
    name: 'Ring Row',
    equipment: Equipment.bodyweight,
    musclesUsed: ['Back', 'Biceps'],
    exerciseCategory: ExerciseCategory.upperPull,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '71',
    name: 'Single Arm Row',
    equipment: Equipment.dumbbell,
    musclesUsed: ['Back', 'Biceps'],
    exerciseCategory: ExerciseCategory.upperPull,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '72',
    name: 'Bicep Curl',
    equipment: Equipment.dumbbell,
    musclesUsed: ['Biceps', ''],
    exerciseCategory: ExerciseCategory.arms,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '73',
    name: 'Cable Curl',
    equipment: Equipment.machine,
    musclesUsed: ['Biceps', ''],
    exerciseCategory: ExerciseCategory.arms,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '74',
    name: 'Cable Extension',
    equipment: Equipment.machine,
    musclesUsed: ['Triceps', ''],
    exerciseCategory: ExerciseCategory.arms,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '75',
    name: 'DB Curl',
    equipment: Equipment.dumbbell,
    musclesUsed: ['Biceps', ''],
    exerciseCategory: ExerciseCategory.arms,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '76',
    name: 'French Press',
    equipment: Equipment.barbell,
    musclesUsed: ['Triceps', ''],
    exerciseCategory: ExerciseCategory.arms,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '77',
    name: 'Hammer Curl',
    equipment: Equipment.dumbbell,
    musclesUsed: ['Biceps', ''],
    exerciseCategory: ExerciseCategory.arms,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '78',
    name: 'Overhead Tricep Extension',
    equipment: Equipment.dumbbell,
    musclesUsed: ['Triceps', ''],
    exerciseCategory: ExerciseCategory.arms,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '79',
    name: 'Skull Crusher',
    equipment: Equipment.dumbbell,
    musclesUsed: ['Triceps', ''],
    exerciseCategory: ExerciseCategory.arms,
    limbInvolvement: LimbInvolvement.bilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '80',
    name: 'Sit Up',
    equipment: Equipment.bodyweight,
    musclesUsed: ['Core', ''],
    exerciseCategory: ExerciseCategory.trunk,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '81',
    name: 'Roll Out',
    equipment: Equipment.bodyweight,
    musclesUsed: ['Core', ''],
    exerciseCategory: ExerciseCategory.trunk,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '82',
    name: 'Knee Raise',
    equipment: Equipment.bodyweight,
    musclesUsed: ['Core', ''],
    exerciseCategory: ExerciseCategory.trunk,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '83',
    name: 'Leg Raise',
    equipment: Equipment.bodyweight,
    musclesUsed: ['Core', ''],
    exerciseCategory: ExerciseCategory.trunk,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '84',
    name: 'Russain Twist',
    equipment: Equipment.bodyweight,
    musclesUsed: ['Core', ''],
    exerciseCategory: ExerciseCategory.trunk,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '85',
    name: 'Plank',
    equipment: Equipment.bodyweight,
    musclesUsed: ['Core', ''],
    exerciseCategory: ExerciseCategory.trunk,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
  Exercise(
    id: '86',
    name: 'Side Plank',
    equipment: Equipment.bodyweight,
    musclesUsed: ['Core', ''],
    exerciseCategory: ExerciseCategory.trunk,
    limbInvolvement: LimbInvolvement.unilateral,
    link: '',
    note: '',
  ),
];
